package com.example.ace.july_25.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ace.july_25.beans.DatasEntity;

import com.example.ace.july_25.db.DatasEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig datasEntityDaoConfig;

    private final DatasEntityDao datasEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        datasEntityDaoConfig = daoConfigMap.get(DatasEntityDao.class).clone();
        datasEntityDaoConfig.initIdentityScope(type);

        datasEntityDao = new DatasEntityDao(datasEntityDaoConfig, this);

        registerDao(DatasEntity.class, datasEntityDao);
    }
    
    public void clear() {
        datasEntityDaoConfig.clearIdentityScope();
    }

    public DatasEntityDao getDatasEntityDao() {
        return datasEntityDao;
    }

}
